// <auto-generated />
namespace Verbarium.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class QuoteNewField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuoteNewField));
        
        string IMigrationMetadata.Id
        {
            get { return "201810300440502_Quote-NewField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
